# Redirect all HTTP requests to HTTPS
server {
    listen 80;
    server_name vodka-kaz.ru www.vodka-kaz.ru;
    return 301 https://www.vodka-kaz.ru$request_uri;
}

# Handle HTTPS requests
server {
    listen 443 ssl;
    server_name vodka-kaz.ru www.vodka-kaz.ru;

    ssl_certificate /etc/nginx/ssl/vodka-kaz.crt;
    ssl_certificate_key /etc/nginx/ssl/vodka-kaz.key;

    # SSL configuration
    ssl_certificate /path/to/your/fullchain.pem;
    ssl_certificate_key /path/to/your/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';

    # Enable Gzip compression
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_proxied any;
    gzip_min_length 1000;

    # Root directory and index file
    root /var/www/html;
    index index.html;

    location = /sitemap.xml {
        root /var/www/html;
        types { application/xml xml; }
        default_type application/xml;
    }

    # Serve static files with caching
    location ~* \.(png|jpg|jpeg|gif|ico|webp|svg)$ {
        expires 6M;
        access_log off;
    }

    # Handle other requests
    location / {
        try_files $uri $uri/ =404;
    }
}
